# Generated by Django 4.2.7 on 2024-01-21 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delete_cart_delete_cartitem'),
        ('Cart', '0004_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cart_item', to='store.product'),
        ),
    ]
