# Generated by Django 5.0.1 on 2024-02-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
